### ISSUE TITLE
Compile errors are swallowed if not run in console

### ISSUE THREAD

**Issue by zabulus** [ibrahimbensalah/Xania.AspNet#10]
We are using xunit VS test adapter. And errors found here:
https://github.com/ibrahimbensalah/Xania.AspNet/blob/c266f96c6a6bb7ca18d33ec684404ca40e907516/Xania.AspNet.Razor/WebViewPageFactory.cs#L105
Won't be able to diagnose, they all written to Console.
I suggest to create new Exception object and add all debug information there: referenced assemblies, compile errors, generated text, etc.

**Comment by ibrahimbensalah** [comment]
package has been updated with suggested change.
