### ISSUE TITLE
Calling action with filters

### ISSUE THREAD

**Issue by mwhelan** [ibrahimbensalah/Xania.AspNet#4]
Hi @ibrahimbensalah. Really interested in this project. Could you provide an example of how I can execute a controller action that has filters on it? For example, I have a LoggingFilter that has been added to GlobalFilters. I'm interested in executing the whole pipeline, with filters, binders, etc.

Thanks

**Comment by ibrahimbensalah** [comment]
Hi, You can register your global action filters as the following

>  GlobalFilters.Filters.Add(new MyActionFilterAttribute());

Your welcome

**Comment by ibrahimbensalah** [comment]
For more detailed example take a look at https://github.com/ibrahimbensalah/Xania.AspNet/tree/master/Xania.AspNet.Simulator.Tests/LinqActions

**Comment by mwhelan** [comment]
Great, that works. Thanks!
